### ISSUE TITLE
getMany with partial result?

### ISSUE THREAD

**Issue by ronag** [Level/abstract-level#39]
I believe currently the getMany API expects an all or nothing result. However, I think it might make sense to allow partial results based on e.g. a high water mark or deadline?

**Comment by vweevers** [comment]
The `getMany()` method has a straight-forward use case, precisely for when memory usage (etc) is _not_ a concern. Otherwise, iterators should be used. Between iterators and `getMany()` there are gaps in functionality, but I'd prefer to close those gaps with (for example) a snapshot API like `db.snapshot().get()`. Rather than diluting `getMany()`.

Your question is a bit vague. What particular gap are you trying to close?

**Comment by ronag** [comment]
I'll sort it with a custom method.
