### ISSUE TITLE
How to check if KEY exists or alternatively check if VALUE exists in all keys

### ISSUE THREAD

**Issue by orangeman12** [Level/abstract-level#69]
how to check if a key exists or alternatively if a value exists in the database
i am using nodejs and making an express app

**Comment by vweevers** [comment]
See https://github.com/Level/community/issues/106, which contains several ways to do it today, and a proposal for doing it with a new API that would have optimal performance.

As for checking whether a value exists, that doesn't fit in the key-centric design of level (or any key-value database). You would have to create an index so that you can lookup values (as keys).

**Comment by orangeman12** [comment]
thank you!
